# Generated by Django 5.2 on 2025-04-08 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='progress',
            field=models.FloatField(default=0),
        ),
    ]
